{{ if and ($.Values.ingress.tls) (ne (.Values.replication.replicationIsReplica) false) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $.Values.ingress.tls.secretName }}
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVVWMxOGt2cFJp
    b2wwUUpCbnVVTy94SEJ1dUNRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF3d1lh
    VzF0ZFdSaUxXVjRZVzF3YkdVdWJHOWpZV3hvYjNOME1CNFhEVEl6TURReApOakEzTkRjek5Gb1hE
    VEkwTURReE5UQTNORGN6TkZvd0l6RWhNQjhHQTFVRUF3d1lhVzF0ZFdSaUxXVjRZVzF3CmJHVXVi
    RzlqWVd4b2IzTjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXUy
    MlYKRWZaRTN6bCsrYzEwUVNOQ2NhV3FsOTZ0Mmhvdm1FYVI3RzVLTTA4d1lUVlBXbHc3TXcrOHB0
    NnY2V2JIdlVQTQpEdHNPK3kvbEpwTllxQjRuWlRENzhzNklhL0huRTlRamx6ZmdQS25SdThXYys1
    REsyN2xqRlVubnRza2hOdWM3CmxsRFRDN0ZRd2pBRUpHa3VvNjd1UkpZenpIM25QdVg5M3kzZUlz
    RGtPZWoxV3FPOGFadTcwK2RoZ2phME1WODgKRitUY2FOc0hvVXRDUUtPRmN1Mm9KOE1lRktKU3VV
    SVB1Q1dRMzkxZXNURHM0WnRzem1hUUFqTWE4azNvZ0xaSApEbDUrZkZqR1BTZGo3dlowSmFFM1M1
    ME85VWljRDNiT2xFMGMwUFZ0dktOYVNZSHFDTDROY1N1Rmx1UkdNRVRSCkVBdmRoWGhtRCtTZGtY
    Mmcwd0lEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVR29vSThWeWVneGpXVzVUQmRDenMKNkluQzcv
    SXdId1lEVlIwakJCZ3dGb0FVR29vSThWeWVneGpXVzVUQmRDenM2SW5DNy9Jd0R3WURWUjBUQVFI
    LwpCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEeUdadUYyZTVZUTlnck5RbmdJ
    LzJmU2p1bmV2CmM0ZHNiQkZTRi9pRGoyNUgycUVYTWQvL0xra0wvYnV2RlJRcWpXZ2g5VlFFejdu
    QmNLcjZGSGdxbzJDNG5uMTEKTi9Gdml2dExrQ1UvdzRxdlV3TVVPbGZMMmo4ZXEvNldIWFA3VEEy
    anQrNEJjT3Q4Zi9CTzAzQWJPd0xRQkUzNwpOWEZoMFIydTE3aVpuMHluakFvaEdBK2dRcGE0ZVRR
    ejFTNGxMUTB2aTg5TDc2cXBBdk1DTFZlYThRZ2RVLzAvCkdvY056RGlpbUc5TVdVZWJScWo2NURu
    Tk5vYkdoS2ZNVUV5Z1BKQ0w1ek5ueS9GcmJSclVOVElna1RHT09zVlgKSEl5N0FOTXZvbzRxV0pl
    blVGRzRNcTJGaEZHTGZsRnpFemRsckhTNmN6WVFEckZ1bWhoOU9ueGZCUT09Ci0tLS0tRU5EIENF
    UlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzdiWlVSOWtUZk9YNzUKelhSQkkwSnhwYXFYM3EzYUdpK1lS
    cEhzYmtvelR6QmhOVTlhWERzekQ3eW0zcS9wWnNlOVE4d08ydzc3TCtVbQprMWlvSGlkbE1Qdnl6
    b2hyOGVjVDFDT1hOK0E4cWRHN3haejdrTXJidVdNVlNlZTJ5U0UyNXp1V1VOTUxzVkRDCk1BUWth
    UzZqcnU1RWxqUE1mZWMrNWYzZkxkNGl3T1E1NlBWYW83eHBtN3ZUNTJHQ05yUXhYendYNU54bzJ3
    ZWgKUzBKQW80Vnk3YWdud3g0VW9sSzVRZys0SlpEZjNWNnhNT3pobTJ6T1pwQUNNeHJ5VGVpQXRr
    Y09YbjU4V01ZOQpKMlB1OW5RbG9UZExuUTcxU0p3UGRzNlVUUnpROVcyOG8xcEpnZW9JdmcxeEs0
    V1c1RVl3Uk5FUUM5MkZlR1lQCjVKMlJmYURUQWdNQkFBRUNnZ0VBVDNDN1ljRVpZT25NUFZITkov
    eXJZV0wvNHQzaG54TkJRQkFOTW9KdWxiL0gKT0RSeHZWRmhVQnVuOEt4ck1BaTl1U1Vldk44eFF0
    c0NpNjZoUWFTQ094d2ZkY0wvUkkxanpWNDVkWk1ieW1xSgorRVhpYXlmc0syUXdzR25DT2hHV3Ir
    QWpPK3RuQUVvMytnNkMrdkhQOEZXcExNM2pCNVlIcVB1dmRtUkpCajR5CjA0U0hIMWRiNVBmaFVB
    TUVQVnJKbmRBYlloSUtiSm10VzRFeW8zQlJpNGxRS3RoMUw5SUxBVVlGOUwzdjM3TTYKblhhb1VB
    Q2VqcXQ3WGFRcGVERmtheGhHOGVnbDJyclFQK2plVUFBM05CV3BGZytJSC9Nc2NhMDVzS1VaeUxE
    OApKcjJPQ2pWTUcwTDR1TTVnWXQxVnBiV1Q5RWsvZXVCbUxpZS8vZElLOVFLQmdRQzhkMjhzNEtr
    OU5KVzZLbjRFClpZUytFWjhhZmJZWnRTYlo5TnE4TUlMcWZQbVgyaWJ2ekNNbC94MitPVnB3aGpo
    NkVnL0RUUDNBZkVoZDhmNzgKc2pJSmFNdFFiVCtEZ2V5UG8vbTBldUl2RUxtQS9hUnlaOFRxSzJm
    SnNOVm0yTDRJQVR5bWxLM2V0a2VKK0dJLwpja296VGZKdExJTXZYQWc5R085UjBLUnJWUUtCZ1FE
    K2x1S0x0aDBaNVc1R1YxRHlybVdQYnN0OUFGRHJpRllwCkxLbWJXZFZkZzRoRUNuUzBEN2s1VURu
    RmN5QjY2bHF2MFBRdVJTSGh6SkV6N2F6Y25XQ0RDeEJ1V1cyZFFaeGgKb1g2eFdUcFRhUEJQSlpY
    TGZaS01MMEY4MWxGMG1nMllPc0xWS2JldHhnenFiVVVTYmVRS3dVeHFxZlJhcFAxNwowUnpxSHpy
    cmh3S0JnR0RCdUhRRHl4OC9GZmVEeFRxZ20rdXd4RXduYWd2OHNydUhONTBTRXNRcjhVQUNvYWJP
    CjJPU3kreVFqOGNoL1FCTjdubGdYK05hUGQ5K3pVOE9NQUtCUUNzRjV0UGZoQmdBZ29Sd0ZVb1h6
    UWlsMURxNGwKbERUY24rWXVRUUVTR1UybXhPcUl2bEx1cGYreFkwOUxiOGl6SmRqaTExN0RFdis3
    QTNLdmVSb1pBb0dBU3BYcAp5UVNSZ2dTMVNlWkswTTVHOHI2QzN4dzRtTWhZZGJlZitPTllud3pw
    M3dVeEs0OXZ0RnJNa2d3b2Q5b3d0MUdBCk9BNEkzeDRQYkNjMWZXeWQyY1prQ2ZBcExPa0w1NDVv
    ajR5VWlkczBpL3QyNXliaXlDOFFBSUxKV2wvSG05R2IKUXRmMTkvTU4xYUF0bkRpVmxwRUswalQ0
    WVpYMHJWR1dKd0QvUWdFQ2dZQjNpUVlsUFdQYUhIOVpMM3JBSm0xdgo1ckZMUExxZE91ZU5Da0pQ
    S0NOQjNsd2dIVUFpQnJrbWJhY1JuYTh4L2xxMWNVWmZHNDFGZUJZMkRRaDdEclUzCk83SEk3ZkRz
    d0NkUHpncHgybysxSTg0WlkwZytSR3FDa2NYKzlZYlk5MHlEL0NsVk1QcERKbk5uSjlONlVkT0kK
    YVcvbk92d1VFUzF6NGxDNCt1ekRpUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
{{ end }}
