{{ if $.Values.replication.replicationIsReplica }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immudb.fullname" . }}-replication-credentials
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
type: Opaque 
data: 
  replication-primary-password: "{{$.Values.replication.replicationPrimaryPassword|b64enc}}"
{{ end }}
