{{- if gt (.Values.replicaCount | toString | atoi) 1 }}
{{- fail "At the moment, you can just have 1 instance of immudb. We are working to raise that limit."}}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "immudb.fullname" . }}
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "immudb.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "immudb.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "immudb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: immudb-storage
        persistentVolumeClaim:
          claimName: {{ include "immudb.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 3322
              protocol: TCP
            - name: metrics
              containerPort: 9497
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /readyz
              port: metrics
            failureThreshold: 9
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
          env:
          - name: IMMUDB_REPLICATION_IS_REPLICA
            value: {{ .Values.replication.replicationIsReplica | quote }}
          {{- if $.Values.replication.replicationIsReplica }}
          - name: IMMUDB_REPLICATION_PRIMARY_HOST
            value: {{ .Values.replication.replicationPrimaryHost | quote }}
          - name: IMMUDB_REPLICATION_PRIMARY_USERNAME
            value: {{ .Values.replication.replicationPrimaryUsername | quote }}
          - name: IMMUDB_REPLICATION_PRIMARY_PASSWORD
            value: {{ .Values.replication.replicationPrimaryPassword | quote }}
            # valueFrom:
            #   secretKeyRef:
            #     name: {{ include "immudb.fullname" . }}-replication-credentials
            #     key: replication-primary-password
          - name: IMMUDB_REPLICATION_PRIMARY_PORT
            value: {{ .Values.replication.replicationPrimaryPort | quote }}
          {{- end}}

          {{- if $.Values.adminPassword }}
          - name: IMMUDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "immudb.fullname" . }}-credentials
                key: immudb-admin-password
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/immudb
            name: immudb-storage
            {{- if $.Values.volumeSubPath.enabled }}
            subPath: {{ $.Values.volumeSubPath.path | quote }}
            {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: immudb-storage
    spec:
      accessModes:
      - ReadWriteOnce
      {{- if .Values.volume.class }}
      storageClassName: {{ .Values.volume.class | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.volume.size }}
