apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-server-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/prom-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
       - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
               - debian11.localdomain
